k2order = {2: [1,2],
           3: [1,2,3],
           4: [4,3,1,2],
           5: [4,1,3,2,5],
           6: [3,6,5,4,2,1],
           7: [6,3,7,2,5,4,1],
           8: [4,8,5,1,3,2,7,6],
           9: [5,9,1,2,8,3,6,7,4],
           10: [5,1,10,3,9,6,8,2,7,4],
           11: [1,11,8,9,10,5,2,3,4,6,7],
           12: [4,6,7,9,3,1,10,11,12,2,8,5],
           13: [5,10,7,1,9,13,2,6,11,3,4,12,8],
           14: [11,8,6,7,10,13,12,3,1,9,4,14,5,2],
           15: [2,13,14,12,6,7,15,5,4,8,10,11,3,1,9],
           16: [1,2,6,10,7,15,16,9,13,4,3,12,11,5,14,8],
           17: [7,8,10,13,4,17,5,15,6,11,3,2,14,1,9,12,16],
           18: [4,10,14,15,5,1,9,11,6,13,17,2,8,12,3,16,7,18],
           19: [1,10,16,11,14,5,6,12,13,9,18,3,7,4,2,17,19,15,8],
           20: [3,5,13,12,18,20,7,15,10,17,6,1,4,8,11,19,16,9,2,14],
           21: [3,6,12,17,9,18,20,5,11,15,7,16,2,21,13,19,1,4,10,8,14],
           22: [3,13,20,22,6,14,8,11,9,12,17,1,16,5,7,18,2,19,10,4,21,15],
           23: [1,8,10,9,14,15,20,19,21,4,23,12,17,18,11,3,2,5,16,6,13,7,22],
           24: [9,15,17,18,21,4,22,23,7,19,10,12,16,14,5,11,2,8,13,6,20,3,1,24],
           25: [3,13,20,22,23,6,24,8,11,9,12,17,1,16,18,5,2,7,25,19,10,4,21,14,15]}

k2title = {
   2: ['Arousal', 
    'Manipulation'],
   3: ['Arousal', 
    'Manipulation', 
    'Language'],
   4: ['Memory', 
    'Arousal', 
    'Vision', 
    'Hearing'],
   5: ['Memory', 
    'Arousal', 
    'Manipulation', 
    'Vision', 
    'Hearing'],
   6: ['Memory', 
    'Reward', 
    'Reaction Time', 
    'Manipulation', 
    'Vision', 
    'Hearing'],
   7: ['Emotion',
    'Reward',
    'Cognitive',
    'Manipulation',
    'Vision',
    'Hearing',
    'Meaning'],
   8: ['Memory',
    'Episodic Memory',
    'Arousal',
    'Cognitive Process',
    'Manipulation',
    'Vision',
    'Perception',
    'Language'],
   9: ['Memory',
    'Anticipation',
    'Reward',
    'Cognitive Process',
    'Manipulation',
    'Vision',
    'Word',
    'Perception',
    'Language'],
   10: ['Memory',
    'Reward',
    'Arousal',
    'Cognitive',
    'Manipulation',
    'Episodic Memory',
    'Retrieval',
    'Vision',
    'Perception',
    'Language'],
   11: ['Memory',
    'Episodic Memory',
    'Emotion',
    'Cognitive',
    'Reward',
    'Arousal',
    'Manipulation',
    'Vision',
    'Hearing',
    'Language',
    'Cognitive Process'],
   12: ['Memory',
    'Retrieval',
    'Episodic Memory',
    'Reward',
    'Anticipation',
    'Emotion',
    'Arousal',
    'Cognition',
    'Manipulation',
    'Vision',
    'Hearing',
    'Language'],
   13: ['Memory',
    'Episodic Memory',
    'Emotion',
    'Reward',
    'Decision Making',
    'Arousal',
    'Cognitive',
    'Manipulation',
    'Retrieval',
    'Vision',
    'Perception',
    'Hearing',
    'Language'],
   14: ['Memory',
    'Retrieval',
    'Episodic Memory',
    'Reward',
    'Decision Making',
    'Arousal',
    'Salience',
    'Cognitive',
    'Manipulation',
    'Hand',
    'Vision',
    'Perception',
    'Language',
    'Emotion'],
   15: ['Memory',
    'Episodic Memory',
    'Recall',
    'Retrieval',
    'Valence',
    'Reward',
    'Anticipation',
    'Emotion',
    'Cognition',
    'Arousal',
    'Manipulation',
    'Cognitive',
    'Vision',
    'Hearing',
    'Language'],
   16: ['Memory',
    'Episodic Memory',
    'Emotion',
    'Retrieval',
    'Reward',
    'Anticipation',
    'Arousal',
    'Thought',
    'Cognitive',
    'Preparation',
    'Vision',
    'Recognition',
    'Perception',
    'Language',
    'Word',
    'Meaning'],
   17: ['Memory',
    'Episodic Memory',
    'Retrieval',
    'Recall',
    'Recognition',
    'Arousal',
    'Reward',
    'Decision Making',
    'Emotion',
    'Cognitive',
    'Preparation',
    'Vision',
    'Familiarity',
    'Hearing',
    'Language',
    'Meaning',
    'Representation'],
   18: ['Memory',
    'Retrieval',
    'Episodic Memory',
    'Recall',
    'Word',
    'Emotion',
    'Decision Making',
    'Cognitive',
    'Reward',
    'Arousal',
    'Cognitive Process',
    'Manipulation',
    'Execution',
    'Vision',
    'Hearing',
    'Language',
    'Speech',
    'Meaning'],
   19: ['Memory',
    'Episodic Memory',
    'Recall',
    'Recognition',
    'Fear',
    'Reward',
    'Reaction Time',
    'Anticipation',
    'Retrieval',
    'Emotion',
    'Arousal',
    'Cognitive',
    'Manipulation',
    'Vision',
    'Hearing',
    'Language Processing',
    'Speech',
    'Language',
    'Word'],
   20: ['Memory',
    'Episodic Memory',
    'Familiarity',
    'Retrieval',
    'Recall',
    'Encoding',
    'Emotion',
    'Decision Making',
    'Reward',
    'Arousal',
    'Cognitive Process',
    'Cognitive',
    'Preparation',
    'Manipulation',
    'Execution',
    'Thought',
    'Vision',
    'Hearing',
    'Language',
    'Meaning'],
   21: ['Memory',
    'Episodic Memory',
    'Retrieval',
    'Recall',
    'Emotion',
    'Decision Making',
    'Feedback',
    'Reward',
    'Salience',
    'Arousal',
    'Attention',
    'Context',
    'Cognitive',
    'Manipulation',
    'Execution',
    'Anticipation',
    'Vision',
    'Hearing',
    'Word',
    'Language',
    'Meaning'],
   22: ['Memory',
    'Episodic Memory',
    'Recall',
    'Remembering',
    'Recognition',
    'Retrieval',
    'Reward',
    'Valence',
    'Emotion',
    'Decision Making',
    'Loss',
    'Anticipation',
    'Arousal',
    'Cognitive',
    'Manipulation',
    'Cognitive Process',
    'Vision',
    'Perception',
    'Language',
    'Hearing',
    'Word',
    'Meaning'],
   23: ['Memory',
    'Episodic Memory',
    'Recall',
    'Recognition',
    'Familiarity',
    'Encoding',
    'Remembering',
    'Retrieval',
    'Fear',
    'Reward',
    'Decision Making',
    'Anticipation',
    'Arousal',
    'Emotion',
    'Cognitive',
    'Preparation',
    'Vision',
    'Perception',
    'Hearing',
    'Language',
    'Word',
    'Meaning',
    'Manipulation'],
   24: ['Memory',
    'Episodic Memory',
    'Retrieval',
    'Recall',
    'Encoding',
    'Recognition',
    'Feedback',
    'Pain',
    'Emotion',
    'Salience',
    'Reward',
    'Decision Making',
    'Valence',
    'Anticipation',
    'Arousal',
    'Reaction Time',
    'Execution',
    'Cognitive Process',
    'Perception',
    'Vision',
    'Speech',
    'Language',
    'Manipulation',
    'Word'],
   25: ['Memory',
    'Episodic Memory',
    'Encoding',
    'Retrieval',
    'Familiarity',
    'Recognition',
    'Recall',
    'Reward',
    'Fear',
    'Emotion',
    'Decision Making',
    'Loss',
    'Anticipation',
    'Arousal',
    'Cognitive',
    'Manipulation',
    'Vision',
    'Preparation',
    'Social Cognition',
    'Perception',
    'Language',
    'Hearing',
    'Semantic Processing',
    'Meaning',
    'Word']}